### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by cynthia143234** [BD2KGenomics/toil-rnaseq#178] opened 2019-03-25 18:24 UTC
Hi, 

I used a cloud system to install toil-rnaseq under python 2.7 and activate it. However, when I'm trying to generate the index and run samples, the errors always occur as follow. Do you know what's the problem of it? 
(toil-rnaseq) [xxx@quserxx yue]$ toil-rnaseq run -h
-bash: toil-rnaseq: command not found

Best, 
Yue

**Comment by jvivian** [comment] 2019-03-25 20:20
Hi @cynthia143234 — This indicates to me that the `toil-rnaseq` package did not get installed. Can you post the commands you used to setup the virtualenv (if any) and how you installed the package?

**Comment by cynthia143234** [comment] 2019-03-25 21:28
>Hi @jvivian 
I used Quest system to do it. The commands are as follow: 
" module load python/anaconda
conda create --no-default-packages -n toil-rnaseq python=2.7
source activate toil-rnaseq
pip install toil-rnaseq"

**Comment by jvivian** [comment] 2019-03-26 00:35
@cynthia143234 — That looks correct to me. Once you run `pip install toil-rnaseq` you should be able to access the `toil-rnaseq` entrypoint. I just tried the following commands on my local laptop and it worked. 

```
conda create --no-default-packages -n toil-rnaseq python=2.7
source activate toil-rnaseq
pip install toil-rnaseq

toil-rnaseq

usage: toil-rnaseq [-h] {generate,config-input,manifest-input,run} ...

                        Toil RNA-seq Workflow
    Computational Genomics Lab, Genomics Institute, UC Santa Cruz

    RNA-seq samples are trimmed, QCed, combined, aligned, and quantified:
        - CutAdapt
        - FastQC
        - STAR -> RSEM
        - Kalisto
        - Hera

    Quickstart:
    1. Type `toil-rnaseq generate` to create an editable manifest and config.
    2. Parameterize the workflow by editing the config.
    3. Fill in the manifest with information pertaining to your samples.
    4. Type `toil-rnaseq run ./jobStore` to execute the workflow locally.

    Please read the README before use and check the github wiki for additional details:
    https://github.com/BD2KGenomics/toil-scripts/tree/master/src/toil_scripts/rnaseq_cgl


positional arguments:
  {generate,config-input,manifest-input,run}
    generate            Generates a config and manifest in the current working directory.
    config-input        Allows user to configure workflow by following prompts.
    manifest-input      Allows user to input samples to the manifest by following prompts.
    run                 Runs the Toil RNA-seq workflow

optional arguments:
  -h, --help            show this help message and exit
```

**Comment by jvivian** [comment] 2019-03-26 03:16
@cynthia143234 — I'm going to close this as I can't reproduce the issue in an isolated environment.

**Closed as completed by jvivian** 2019-03-26 03:16 UTC
